"""Input records retain original evidence and explicit provenance coordinates."""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, Literal

from pydantic import Field

from .base import ExtractionModel


class RetrievedRecord(ExtractionModel):
    document_id: str = Field(
        description="Actual source document ID; must be supplied by retrieval."
    )
    citation: str = Field(
        description="Actual retrieval citation; never generated by the extraction model."
    )
    text: str = Field(
        description="Original retrieved excerpt, preserved verbatim as untrusted evidence."
    )
    markdown_path: str | None = Field(
        default=None, description="Supplied Markdown path; null if absent."
    )
    source_start: int | None = Field(
        default=None, description="Supplied start offset; null if absent."
    )
    source_end: int | None = Field(default=None, description="Supplied end offset; null if absent.")
    offset_coordinate_system: Literal["selected_excerpt", "markdown", "unknown"] = Field(
        default="unknown",
        description="Known coordinates for supplied offsets; unknown if unspecified.",
    )
    source_length: int | None = Field(
        default=None,
        description="Known source length in the same coordinate system; null if absent.",
    )
    truncated: bool = Field(
        default=False, description="Whether upstream evidence selection cut text short."
    )
    company: str | None = Field(
        default=None, description="Supplied catalog issuer name; null if absent."
    )
    ticker: str | None = Field(default=None, description="Supplied catalog ticker; null if absent.")
    document_type: str | None = Field(
        default=None, description="Supplied catalog document type; else null."
    )
    document_date: str | None = Field(
        default=None, description="Supplied catalog date label; not an inferred effective date."
    )
    period_end: str | None = Field(
        default=None, description="Supplied catalog period label; else null."
    )
    role: str | None = Field(default=None, description="Supplied catalog document role; else null.")
    notes: str | None = Field(
        default=None,
        description="Catalog descriptions only, not quoted filing evidence; else null.",
    )

    @classmethod
    def from_record(cls, record: RetrievedRecord | Mapping[str, Any]) -> RetrievedRecord:
        """Adapt existing content-key dictionaries without filling missing provenance."""
        if isinstance(record, cls):
            return record
        values = {key: record[key] for key in cls.model_fields if key in record}
        if "text" not in values and "content" in record:
            values["text"] = record["content"]
        return cls.model_validate(values)

    def envelope(self) -> dict[str, Any]:
        """Separate filing evidence from catalog context and retrieval diagnostics."""
        result = {"document_id": self.document_id, "citation": self.citation, "text": self.text}
        for name in ("markdown_path", "source_start", "source_end"):
            if getattr(self, name) is not None:
                result[name] = getattr(self, name)
        result["catalog_context"] = {
            name: getattr(self, name)
            for name in (
                "company",
                "ticker",
                "document_type",
                "document_date",
                "period_end",
                "role",
                "notes",
            )
            if getattr(self, name) is not None
        }
        result["retrieval_metadata"] = {
            "offset_coordinate_system": self.offset_coordinate_system,
            "source_length": self.source_length,
            "truncated": self.truncated,
        }
        return result
